### ISSUE TITLE
WebStorm support

### ISSUE THREAD

**Issue by mnasyrov** [leomillon/uuid-generator-plugin#1]
Thank for the plugin!
Please make it be available for WebStorm.

**Comment by leomillon** [comment]
Hi @mnasyrov !

Should be now available for all IntelliJ products since v1.0.1 : [UUID Generator on Jetbrains plugins repository](https://plugins.jetbrains.com/idea/plugin/8320-uuid-generator)

Just tried on WebStorm 2016.3.2.

Tell me if it is working for you :)

**Comment by mnasyrov** [comment]
Just tried in WebStorm, works great!
