### ISSUE TITLE
Feature: live templates

### ISSUE THREAD

**Issue by WuglyakBolgoink** [leomillon/uuid-generator-plugin#12]
Hallo @leomillon,

is it possible to use your plugin in live-templates in webstorm?

**Comment by leomillon** [comment]
Hello @WuglyakBolgoink !

I'm not sure to understand how you want this plugin to be "usable" in the Webstorm live-templates.

IntelliJ live-templates (https://www.jetbrains.com/help/idea/using-live-templates.html) are pre-generated code snippets that can re-use local variables in your code. So it's not possible to "generate" a random UUID when the live-template will be triggered.

I'm not sure to have fully understood your wish but if it's really about generating a random UUID via a live-template, that's not possible :/

**Comment by leomillon** [comment]
I close this issue since no answer has been provided since a while...

**Comment by WuglyakBolgoink** [comment]
Hallo @leomillon 

sorry, it was missed from notification.

my Idea was to have some snippets in live-editor

for example - if I create a new snippet for some blocks like

```
class XXX {
   private id: "$UUID$";
}
```

then I will have at the end

```
class XXX {
   private id: "8451ce10-9c15-4c78-8b73-68668649610e";
}
```

**Comment by leomillon** [comment]
No problem, but as I said, it's currently not possible to execute custom code to replace live template content.

**Comment by WuglyakBolgoink** [comment]
@leomillon oki! np!

**Comment by leomillon** [comment]
Hi @WuglyakBolgoink 

Just to inform you that you might be interested in this new feature I'm working on: https://github.com/leomillon/uuid-generator-plugin/issues/46#issuecomment-830228530

**Comment by WuglyakBolgoink** [comment]
@leomillon this is a great feature!!!
