### ISSUE TITLE
ULID feature request

### ISSUE THREAD

**Issue by xtrasmal** [leomillon/uuid-generator-plugin#13]
Hi there, 

I am using your plugin a lot, but lately I am getting requests to return an ULID instead of an UUID.
I came across this: https://github.com/f4b6a3/ulid-creator and was wondering if it is easy for you to include the creation ULID's as well as creating UUID's in a future update?

Based on the spec ULID's can look like this:

- **01706d6c-6aac-80bd-7ff5-f660c2dd58ea**
- **01E1PPRTMSQ34W7JR5YSND6B8T**
- **01ecz13fmqxmtx6z46xxdhb9fx**

**Comment by leomillon** [comment]
Hi!

I'm going to have a look at how it could be combined why the current UUID format customization.

I'm thinking of add an "Id type" which will be `uuid` by default but could be changed to `ulid`.

The remaining behavior of the plugin should stay the same.

What do you think?

**Comment by xtrasmal** [comment]
Hello, 

I was thinking about it yesterday and I like the idea. 

So, in the plugin's options you can (for example) go to the settings and there would be an option, 
with a description: `Please select the default ulid format:`?

- [] 01706d6c-6aac-80bd-7ff5-f660c2dd58ea
- [x] 01ecz13fmqxmtx6z46xxdhb9fx  
- [] 01E1PPRTMSQ34W7JR5YSND6B8T

Yesterday I had to create a `uuid` and a directly afterwards a `ulid`. A couple of times while creating ENUMS and Array collections.  The collections look like this: 

```
[
    'id'         =>    '01706d6c-6aac-80bd-7ff5-f660c2dd58ea', 
    'ref_id'     =>    '01ecz13fmqxmtx6z46xxdhb9fx',
    'label'      =>    'Something'
]
```

For the `uuid` I have your plugin's action to create a fresh random `uuid` on my main toolbar. 
Another way I create a `uuid` with your plugin, is to tap `shift-key shift-key` and then type `uuid` and press `enter`.

It would be nice to be able to do the same for `ulid` in the future:

For the `ulid` I have your plugin's action to create a fresh random `ulid` on my main toolbar. 
Another way I create a `ulid` with your plugin, is to tap `shift-key shift-key` and then type `ulid` and press `enter`.

**Comment by leomillon** [comment]
Ok so may be it should be better to introduce some kind of a multi-tab panel to be able to handle the `uuid` and `ulid` formats separately with dedicated shortcuts for each.

Thank for sharing your use-case, I'll see what I can do to implement this new need.
