### ISSUE TITLE
Support mullti-cursor mode

### ISSUE THREAD

**Issue by danielesegato** [leomillon/uuid-generator-plugin#2]
If you select multiple places with CTRL+ALT+SHIFT+CLICK and start typing it types on each place.

I think generating an uuid in this situation should generate a different uuid for each cursor.

What's actually happen instead is it generates an uuid on the last cursor only.

**Comment by leomillon** [comment]
Here is your feature : https://plugins.jetbrains.com/plugin/8320-uuid-generator/update/33960

I also added support for the multi-selection replacement :)

Tell me if it answers well your request.

**Comment by danielesegato** [comment]
Awesome!!!
works like a charm! thank you
