### ISSUE TITLE
Feature request - replacing all found UUID's in file

### ISSUE THREAD

**Issue by brzuchal** [leomillon/uuid-generator-plugin#27]
Would it be possible to introduce a feature that replaces all file found UUIDs with newly generated ones?

**Comment by leomillon** [comment]
Hello @brzuchal!

That should be possible but, instead of focusing only on "all UUIDs inside a file", this could be "all UUIDs inside the selection".

This way you could easily choose the search zone by selecting either the entire file or just a section of it.

How about that?

**Comment by brzuchal** [comment]
@leomillon that would be great, thanks

**Comment by brzuchal** [comment]
But one note. If there are more instances of certain UUID in the selection they all should be replaced with the same generated one.

**Comment by leomillon** [comment]
@brzuchal it's just been released, I hope this will suit your needs :)

https://plugins.jetbrains.com/plugin/8320-uuid-generator

Do not hesitate if there is an issue

**Comment by brzuchal** [comment]
OMG that was fast 😅
