### ISSUE TITLE
False positive highlight of CUID

### ISSUE THREAD

**Issue by ste93cry** [leomillon/uuid-generator-plugin#40]
Similar to #17, but for CUID (didn't even know it existed btw :sweat_smile:). As you can see in the attached screenshots, the plugin highlitghts things that it should not. Probably, just ensuring that the entire word matches the expected pattern and not just a subset of it would be enough to fix the issue. Better would be to be able to configure for which types the highlighting is enable, so that for example if I know that I don't use CUID in my project I can disable its highlighting and reduce false positives

![Schermata del 2021-02-26 10-45-10](https://user-images.githubusercontent.com/1770485/109284504-36e20200-7820-11eb-9189-b488d4f5545d.png)
![Schermata del 2021-02-26 10-44-49](https://user-images.githubusercontent.com/1770485/109284514-39445c00-7820-11eb-9b1f-95a8fe15bb50.png)

PhpStorm 2020.3.2
Build #PS-203.7148.74
Plugin version 4.3.0

**Comment by leomillon** [comment]
Hello @ste93cry !

Thanks for this issue report, I'll look into it.

Just for you to know, you can indeed already enable/disable the highlighting per "ID type" ;)

<img width="1109" alt="Capture d’écran 2021-02-26 à 11 00 32" src="https://user-images.githubusercontent.com/1232793/109286117-26328b80-7822-11eb-87f3-ef61c685bdb1.png">

**Comment by ste93cry** [comment]
>you can indeed already enable/disable the highlighting per "ID type

I didn't know that either :smiley: Nice!

**Comment by leomillon** [comment]
Just pushed a quick fix into release `4.3.1`

However, there might be some cases where there still might be false positives (for example if you create a class with a name starting `C` and followed by 24 chars) :/

I may be could add some stronger checks like I did for the other types but I have to understand a bit more how the CUID format is working

**Comment by leomillon** [comment]
Ok I added the same "improvement" I used for the other types: the valid ID format should at least contain 2 numbers.

Available in the last published release: `4.3.2`

Do not hesitate if there are still issues with these improvements.

**Comment by ste93cry** [comment]
Thank you for the really fast fix, much appreciated 👍
