### ISSUE TITLE
Feature Request: UUID in file/code templates

### ISSUE THREAD

**Issue by adrianrudnik** [leomillon/uuid-generator-plugin#41]
After failing to find any way to insert newly generated UUIDs into file templates, I fall back to this very nice plugin.

I use it to generate predefined entity/model IDs for functional tests, like a user must always have the same ID to be able to query it for certain endpoints.

Would it be possible to have an option in the settings to automatically inject variables into the file templates?

As I understand, those variables are precomposed strings, so `$UUID$` would always be the same value. Maybe have a number input or generate 50 variables (or a simple integer configuration setting), like `$UUID1$`, `$UUID2` and so on?

I already tried the new selection replace feature from #27, but that does not work on cases like

```php
const ADMIN_ACCOUNT_ID = 'e188f027-39e9-4d6b-868a-2ba00aecc9d0';
const ADMIN_DEVICE_ID = '40db59b9-8249-4423-a840-9f4ae07f8280';
```

where I would need to right-click every single string and replace it (which is not faster then hitting alt+insert and generate). Multi select cursor selections also have no effect with this feature.

Similar plugins could not be found, only https://github.com/vkravets/FileTemplatesVariable seems to work with variable injection, but also provides no means to inject generated uuids.

Is this something that could be in scope of this plugin?

**Comment by leomillon** [comment]
Hi @adrianrudnik !

I'm not sure to really understand what you're trying to achieve with these file templates.

Could you provide a "full" example of the user journey you're doing and what you would like to automate in it please?

**Comment by adrianrudnik** [comment]
I would like to use a file template for function test case fixtures. The default template right now for that has the following repeated parts:

```php
namespace App\DataFixtures\Test\T1;

class T114TestFixture extends Fixture implements DependentFixtureInterface, FixtureGroupInterface
{
    public const GROUP = 'test.functest.t114';

    public const DOMAIN = 'localhost:4001';

    public const ADMIN_ACCOUNT_ID = 'e188f027-39e9-4d6b-868a-2ba00aecc9d0';
    public const ADMIN_DEVICE_ID = '40db59b9-8249-4423-a840-9f4ae07f8280';

    public const PROJECT_ID = '310d8292-d333-4e7e-a7cc-2a31525cfb4d';
    public const STORAGE_ID = '019528c4-d767-417d-8e0f-7861e381555c';
    public const MAILER_ID = '085aab8c-946f-4919-880c-93700ba1c738';
    public const BRANDING_ID = 'c6ea3279-c72e-4be5-aae6-36c1ab3ef296';

    public const UNIT_ID = '8911d094-5be8-4ffa-929f-a63d426009f3';
    public const LOCALITY_ID = '0896261b-e706-4556-a2c3-9bd76ed13d61';
    public const LOCALITY_SECTION_ID = '11f9b713-fe65-4005-acad-4ae7307ca64f';

    public const SCHEDULE_ID = 'a72bd175-ad31-4547-82e9-93804e47a994';

    public static function getGroups(): array
    {
        return [
            T0TestFixture::GROUP,
            self::GROUP,
        ];
    }

    public function getDependencies(): array
    {
        return [
            PrimaryWorkspaceTestFixture::class,
        ];
    }

    public function load(ObjectManager $manager)
    {
        // Setup
        $this->spawnProject(self::PROJECT_ID);
        $this->spawnAdminAccount(self::ADMIN_ACCOUNT_ID);
        // ..
    }
}
```

This is a fixture that is loaded pre running the functional tests that assume a common scenario. For every test case number, we spawn a clean new project that does a setup that allows for the specific feature or data set.

**Comment by adrianrudnik** [comment]
Maybe simplify the whole request a bit:

Is there any way to replace all UUIDs with new ones, even if they are just strings? Right now, i am trying to select the block and try to replace them via context actions, but there is no option for it, like #27 introduces. It just works on if I right-click a single UUID.

Another approach, would it be possible to replace all specific UUIDs (like `'00000000-0000-0000-0000-000000000000'`) with a new value via context option?

I "just" thought that a file template would be the solution as this type of file exists pretty often with a basic setup. I found that Jetbrains really missed the ball because there is no way to add a generated value somewhere in a file template. Just predefined variables and the cursor position, the rest is pretty restricted.

**Comment by leomillon** [comment]
So when you're saying that the feature introduced in #27 only works if you are right-clicking on a single UUID, have you tried to select the target block and use the "find action" feature to replace all the uuids found in the selected block?

Here is an illustration of the feature with your file:
![uuids_replacement_demo](https://user-images.githubusercontent.com/1232793/110211210-cf6a2900-7e95-11eb-8b58-60ca90287d76.gif)

So far, as I understand, this feature should do the trick, right?

**Comment by adrianrudnik** [comment]
Ah there it is hiding, looked through the right click menu after the selection, looking through the actions solved it, thanks!

**Comment by adrianrudnik** [comment]
@leomillon Ah sorry for the late reply but that looks awesome! Thanks, I hope you get enough support for this plugin and all the work :)
