### ISSUE TITLE
Clipboard support

### ISSUE THREAD

**Issue by mfulton26** [leomillon/uuid-generator-plugin#6]
Sometimes I'm actually trying to get a UUID to place into a different program so if I could have an action to copy a random UUID straight to my clipboard that would be awesome. Thank you.

**Comment by leomillon** [comment]
Hello @mfulton26 !

Good idea, I just finished and published it in the 2.1.0 version (see the Jetbrains plugin page https://plugins.jetbrains.com/plugin/8320-uuid-generator )

The new action is called "Generate UUID to clipboard" with a default shortcut `shift + meta + alt + U` then `shift + meta + alt + C`.

It should display a small "balloon popup" with the generated UUID available in your clipboard ;)
<img width="603" alt="clipboard_popup_message_screenshot" src="https://user-images.githubusercontent.com/1232793/58106034-bc666600-7be7-11e9-8882-25ebe10628b5.png">

**Comment by mfulton26** [comment]
Awesome. Thank you!
