### ISSUE TITLE
Nil UUID generator action

### ISSUE THREAD

**Issue by ste93cry** [leomillon/uuid-generator-plugin#76]
I was wondering if it makes sense for the plugin to provide an action to be able to generate a [nil UUID](https://datatracker.ietf.org/doc/html/rfc4122#section-4.1.7) whose value is `00000000-0000-0000-0000-000000000000`. Use case is mostly all places (I think tests are the most common) where you don't care about a real UUID but just about the format: having to remember how many characters there are for each segment or having to search the value takes time that would be better spent in other ways. I don't know Kotlin, but I would be happy to try implementing the feature if you agree

**Comment by leomillon** [comment]
Hi @ste93cry !

I honestly don't really see the point of this feature as it's a "pre-defined" value. So this means you can easily use a live template to generate it.

It's nice to know that it exists but never seen it anywhere ^^

Also, I discovered yesterday a new plugin JetBrains just plugin: [Test Data](https://plugins.jetbrains.com/plugin/16873-test-data)

You can easily defined your custom generators and I've to see how the UUID plugin and this new Test Data generator can live together in a near future

Here are some screenshots about Test Data I made (found nothing on the official plugin page):
<img width="632" alt="Capture d’écran 2021-07-29 à 09 01 26" src="https://user-images.githubusercontent.com/1232793/127447115-c521f41a-6944-4923-9e47-12be87c7ebda.png">
<img width="1094" alt="Capture d’écran 2021-07-29 à 09 01 54" src="https://user-images.githubusercontent.com/1232793/127447124-5753cd34-856f-4b55-bcc6-24cbee2a0392.png">
<img width="1094" alt="Capture d’écran 2021-07-29 à 09 02 03" src="https://user-images.githubusercontent.com/1232793/127447132-5aae4a68-63f5-40c1-848e-b7f93cdf1f25.png">
<img width="1094" alt="Capture d’écran 2021-07-29 à 09 02 17" src="https://user-images.githubusercontent.com/1232793/127447140-d286e9c6-5b08-4ec2-823e-8b067a17f177.png">

**Comment by ste93cry** [comment]
>I honestly don't really see the point of this feature as it's a "pre-defined" value. So this means you can easily use a live template to generate it

Sure, my reasoning was that since this feature is so small that it doesn't add any maintenance burden to the plugin and given that it plays well with the scope of this plugin which is to generate UUIDs, it made sense to have it here. Feel free to close this issue anyway
