### ISSUE TITLE
Plugin-setting to enable/disable line in context menu

### ISSUE THREAD

**Issue by Halanson** [leomillon/uuid-generator-plugin#86]
This is a feature request.

The plugin is working fine, the only problem I have is that my context menu is now too long due to the nine new lines this plugin adds to it. I only use UUIDs and have no need of ULIDs and CUIDs. That is why I would like to remove the (for me) unnecessary six additional lines.

My request is to add an enable/disable checkbox to all three settings tabs of UUID, ULID and CUID to enable/disable each section of the *IDs in the context menu.

![image](https://user-images.githubusercontent.com/20627910/133679009-e16c12e2-9850-44ed-9480-b7046e3bde4b.png)

**Comment by leomillon** [comment]
Hi @Halanson,

I see how this can be annoying :/

I didn't notice as I mostly use shortcuts to generate them.

I'll try to add this configuration as soon as I can!
